// Loading Screen
export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const ADD_HISTORY = "ADD_HISTORY";

// User Section
// List of User
export const GET_LIST_USER_SAGA = "GET_LIST_USER_SAGA";
export const GET_LIST_USER_REDUCER = "GET_LIST_USER_REDUCER";
// User Create
export const CREATE_USER_SAGA = "CREATE_USER_SAGA";
export const PASSWORD = "PASSWORD";
export const NEW_USER_LOGIN = "NEW_USER_LOGIN";

// User Delete
export const DELETE_USER_SAGA = "DELETE_USER_SAGA";

// User Login
export const USER_LOG_IN = "USER_LOG_IN";
export const USER_SIGNIN_API = "USER_SIGNIN_API";

// User Edit
export const SET_SUBMIT_EDIT_USER = "SET_SUBMIT_EDIT_USER";
export const OPEN_FORM_EDIT_USER = "OPEN_FORM_EDIT_USER";
export const EDIT_USER_SAGA = "EDIT_USER_SAGA";

// PROJECT
// Project Category
export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";
export const GET_ALL_PROJECT_CATEGORY_REDUCER =
  "GET_ALL_PROJECT_CATEGORY_REDUCER";

// Create Project
export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";

// Get Project List
export const GET_PROJECT_LIST_SAGA = "GET_PROJECT_LIST_SAGA";
export const GET_PROJECT_LIST_REDUCER = "GET_PROJECT_LIST_REDUCER";

// MODAL DRAWER
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";

// Edit Project
export const SET_SUBMIT_EDIT_PROJECT = "SET_SUBMIT_EDIT_PROJECT";
export const EDIT_PROJECT_SAGA = "EDIT_PROJECT_SAGA";

// Delete Project
export const DELETE_PROJECT_SAGA = "DELETE_PROJECT_SAGA";

// Tooltip
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";

// Add member
export const SEARCH_USER_SAGA = "SEARCH_USER_SAGA";
export const SEARCH_USER_REDUCER = "SEARCH_USER_REDUCER";
export const ASSIGN_USER_TO_PROJECT_SAGA = "ASSIGN_USER_TO_PROJECT_SAGA";

//  add member by Project Id
export const SEARCH_USER_BY_PROJECT_ID_SAGA = "SEARCH_USER_BY_PROJECT_ID_SAGA";
export const SEARCH_USER_BY_PROJECT_ID_REDUCER =
  "SEARCH_USER_BY_PROJECT_ID_REDUCER";
// Remove member
export const REMOVE_USER_FROM_PROJECT_SAGA = "REMOVE_USER_FROM_PROJECT_SAGA";

// Get Project Detail
export const GET_PROJECT_DETAIL_SAGA = "GET_PROJECT_DETAIL_SAGA";
export const GET_PROJECT_DETAIL_REDUCER = "GET_PROJECT_DETAIL_REDUCER";

// Create Task
export const OPEN_FORM_CREATE_TASK = "OPEN_FORM_CREATE_TASK";
export const SET_SUBMIT_CREATE_TASK = "SET_SUBMIT_CREATE_TASK";
export const CREATE_TASK_SAGA = "CREATE_TASK_SAGA";

//Get Task Detail
export const GET_TASK_DETAIL_SAGA = "GET_TASK_DETAIL_SAGA";
export const GET_TASK_DETAIL_REDUCER = "GET_TASK_DETAIL_REDUCER";

// task type
export const GET_ALL_TASK_TYPE_SAGA = "GET_ALL_TASK_TYPE_SAGA";
export const GET_ALL_TASK_TYPE_REDUCER = "GET_ALL_TASK_TYPE_REDUCER";

// Remove task
export const REMOVE_TASK_SAGA = "REMOVE_TASK_SAGA";

// Priority Type
export const GET_ALL_PRIORITY_TYPE_SAGA = "GET_ALL_PRIORITY_TYPE_SAGA";
export const GET_ALL_PRIORITY_TYPE_REDUCER = "GET_ALL_PRIORITY_TYPE_REDUCER";

// Get Status Type
export const GET_ALL_STATUS_TYPE_REDUCER = "GET_ALL_STATUS_TYPE_REDUCER";
export const GET_ALL_STATUS_TYPE_SAGA = "GET_ALL_STATUS_TYPE_SAGA";

// Update Task Detail
export const CHANGE_TASK_DETAIL = "CHANGE_TASK_DETAIL";
export const CHANGE_TASK_ASSIGNEE = "CHANGE_TASK_ASSIGNEE";
export const REMOVE_TASK_ASSIGNEE = "REMOVE_TASK_ASSIGNEE";
export const UPDATE_TASK_SAGA = "UPADTE_TASK_SAGA";
export const HANDLE_CHANGE_POST_API_SAGA = "HANDLE_CHANGE_POST_API_SAGA";

// Update Task Status
export const UPDATE_TASK_STATUS_SAGA = "UPDATE_TASK_STATUS_SAGA";

// Comment Section
// Get all comments
export const GET_ALL_COMMENT_SAGA = "GET_ALL_COMMENT_SAGA";
export const GET_ALL_COMMENT_REDUCER = "GET_ALL_COMMENT_REDUCER";

// Insert new comment
export const INSERT_COMMENT_SAGA = "INSERT_COMMENT_SAGA";
export const INSERT_COMMENT_REDUCER = "INSERT_COMMENT_REDUCER";

// Delete Comment
export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA";

// Update Commetn
export const UPDATE_COMMENT_SAGA = "UPDATE_COMMENT_SAGA";
